### PR TITLE
Fix xtrans premultiply, reduce memory usage, also some small speedups

### PR DESCRIPTION
**Pull request by heckflosse**

### CODE REVIEW

**Comment by heckflosse** [comment]
Some remarks to the commits in this branch:

`Fix xtrans premultiply` ist just a fix for xtrans files, which were not handled correctly before

`Reduce memory usage. Also some small speedups` reduces memory usage anf buffer ping-pong when bayer-ca-correction is uses and adds some #pragma omp stuff

`Do not reallocate memory if matrix size does not change` reduces memory reallocations when adjusters are changed afer loading an image and leads to some speedups in this case

`Reduce buffer ping-pong for hl reconstruction settings 0 and 1 and for whitebalance` does what its topic sais and gives also speedups for this cases.

`Further speedups, mainly by reducing buffer ping-pong` does what its topic sais and gives also speedups for this cases.

**Comment by CarVac** [comment]
I already looked at the code and everything makes sense.

When i get home shortly I'll test it.

**Comment by CarVac** [comment]
On my 2700X, the 1500px previews were 14% faster including demosaicing, and the full res renders were 22% faster not including demosaicing.

**Comment by heckflosse** [comment]
@CarVac 
> On my 2700X, the 1500px previews were 14% faster including demosaicing, and the full res renders were 22% faster not including demosaicing.

permantly small improvemts lead to large improvemets at long term :-)

**Pull request merged**
